vm_num = 1
vm_node_name = "nginx"

Vagrant.configure("2") do |config|

  (1..vm_num).each do |i|

    config.vm.define "#{vm_node_name}-0#{i}" do |node|

      # 设置虚拟机的Box
      node.vm.box = "bento/centos-7.4"

      # 设置虚拟机的主机名
      node.vm.hostname="#{vm_node_name}-0#{i}"

      # 设置虚拟机的IP
      node.vm.network "private_network", ip: "192.168.100.10#{i}"

      # 设置主机与虚拟机的共享目录
      # node.vm.synced_folder "~/Desktop/share", "/home/vagrant/share"

      # VirtaulBox相关配置
      node.vm.provider "virtualbox" do |v|

        # 设置虚拟机的名称
        v.name = "#{vm_node_name}-0#{i}"

        v.memory = 2048

        # 设置虚拟机的CPU个数
        v.cpus = 1
      end

      # 使用shell脚本进行软件安装和配置
      node.vm.provision "shell", inline: <<-SHELL
        # 安装基本组件
        /vagrant/.setting/install.sh

        # 配合国内yum源
        mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.backup
        wget -O /etc/yum.repos.d/CentOS-Base.repo http://mirrors.163.com/.help/CentOS7-Base-163.repo
        yum makecache

        # 添加用户ifneolse
        /vagrant/.setting/add_user.sh ifnoelse ifnoelse

        # 设置用户ssh key登陆
        /vagrant/.setting/ssh_auth.sh ifnoelse

        # 修改时区
        ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

        # 修改hostname
        echo "#{vm_node_name}-0#{i}">/etc/hostname

        # 添加本地hosts解析
        for i in {1..#{vm_num}};do echo "192.168.100.10${i}	#{vm_node_name}-0${i}">>/etc/hosts;done

        # 关闭防火墙
        systemctl stop firewalld
        systemctl disable firewalld

        # 关闭selinux
        setenforce 0
        sed -i 's/SELINUX=permissive/SELINUX=disabled/g' /etc/selinux/config

        # 禁用IPv6
        sysctl -w net.ipv6.conf.all.disable_ipv6=1
        sysctl -w net.ipv6.conf.default.disable_ipv6=1
        echo "net.ipv6.conf.all.disable_ipv6 =1">>/etc/sysctl.conf
        echo "net.ipv6.conf.default.disable_ipv6 =1">>/etc/sysctl.conf

        # 修改nginx配置文件路径，便于开发测试
        echo "include /vagrant/resources/nginx/*.nginx;" > /etc/nginx/nginx.conf
      SHELL
      # node.ssh.private_key_path = ".setting/private_key"
      # node.ssh.username = "ifnoelse"
    end
  end
end