vm_num = 4

Vagrant.configure("2") do |config|

  (1..vm_num).each do |i|

    config.vm.define "node-0#{i}" do |node|

      # 设置虚拟机的Box
      node.vm.box = "bento/centos-7.4"

      # 设置虚拟机的主机名
      node.vm.hostname="node-0#{i}"

      # 设置虚拟机的IP
      node.vm.network "private_network", ip: "192.168.100.10#{i}"

      # 设置主机与虚拟机的共享目录
      # node.vm.synced_folder "~/Desktop/share", "/home/vagrant/share"

      # VirtaulBox相关配置
      node.vm.provider "virtualbox" do |v|

        # 设置虚拟机的名称
        v.name = "node-0#{i}"

        # 设置虚拟机的内存大小
        v.memory = 2048

        # 设置虚拟机的CPU个数
        v.cpus = 1
      end

      # 使用shell脚本进行软件安装和配置
      node.vm.provision "shell", inline: <<-SHELL

        mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.backup
        wget -O /etc/yum.repos.d/CentOS-Base.repo http://mirrors.163.com/.help/CentOS7-Base-163.repo
        yum makecache

        /vagrant/.setting/install.sh

        # yum -y install zlib*
	    # yum -y install openssl
        # wget https://www.python.org/ftp/python/3.6.3/Python-3.6.3.tgz
        # mv Python-3.6.3.tgz /usr/local/src/
        # cd /usr/local/src/
        # sudo tar -xzvf Python-3.6.3.tgz
        # cd Python-3.6.3
        # ./configure --prefix=/usr/local/python3
        # make all
        # make install
        # ln -s /usr/local/python3/bin/python3 /usr/bin/python3
        # ln -s /usr/local/python3/bin/pip3 /usr/bin/pip3

        /vagrant/.setting/add_user.sh ifnoelse
        /vagrant/.setting/ssh_auth.sh ifnoelse

        ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

        echo "node-0#{i}">/etc/hostname

        for i in {1..#{vm_num}};do echo "192.168.100.10${i}	node-0${i}">>/etc/hosts;done

        systemctl disable firewalld
        systemctl enable docker

        sed -i 's/SELINUX=permissive/SELINUX=disabled/g' /etc/selinux/config

        sysctl -w net.ipv6.conf.all.disable_ipv6=1
        sysctl -w net.ipv6.conf.default.disable_ipv6=1
        echo "net.ipv6.conf.all.disable_ipv6 =1">>/etc/sysctl.conf
        echo "net.ipv6.conf.default.disable_ipv6 =1">>/etc/sysctl.conf

        python /vagrant/.k8s/k8s.py "node-01" "node-0#{i}"

        groupadd docker
        usermod -aG docker ifnoelse
	    sudo mkdir -p /etc/docker
	    echo '{"registry-mirrors": ["https://d6at4uvr.mirror.aliyuncs.com"]}'> /etc/docker/daemon.json
	    sudo systemctl daemon-reload
        sudo systemctl restart docker
      SHELL
      # node.ssh.private_key_path = ".setting/private_key"
      # node.ssh.username = "ifnoelse"
    end
  end
end